[package]
name = "predictive_mev_bot"
version = "0.1.0"
edition = "2021"

[lib]
name = "predictive_mev_bot"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
futures-util = "0.3"
alloy = { version = "0.2", features = ["providers", "signers", "network", "rpc-types-eth", "contract", "pubsub", "signer-local", "transports"] }
rayon = "1.10"
num-bigint = "0.4"
num-traits = "0.2"

[[test]]
name = "strict_tests"
path = "tests/strict_tests.rs"
